AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  sam-app-python

  Sample SAM Template for sam-app-python

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3
    MemorySize: 128

Resources:
  HelloWorldFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: functions/hello_world/
      Handler: app.lambda_handler
      Runtime: python3.10
      Layers:
        - !Ref HelloLayer
        - !Ref RequestLayer
      Architectures:
        - x86_64
  HelloWorldFunctionImage:
    Type: AWS::Serverless::Function
    Properties:
      PackageType: Image
      Architectures:
        - x86_64
    Metadata:
      DockerTag: python3.10-v1
      DockerContext: ./
      Dockerfile: ./functions/hello_world_image/Dockerfile
  HelloLayer:
    Type: AWS::Serverless::LayerVersion
    Properties: 
      LayerName: hello_layer
      ContentUri: ./layers/hello_layer/
      CompatibleRuntimes:
        - python3.10
      RetentionPolicy: Retain
    Metadata:
      BuildMethod: python3.10
  RequestLayer:
    Type: AWS::Serverless::LayerVersion
    Properties: 
      LayerName: request_layer
      ContentUri: ./layers/request_layer/
      CompatibleRuntimes:
        - python3.10
      RetentionPolicy: Retain
    Metadata:
      BuildMethod: makefile
