AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  sam-app-python

  Sample SAM Template for sam-app-python

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3
    MemorySize: 128

Resources:
  HelloWorldFunction:
    Type: AWS::Serverless::Function
    Properties:
      PackageType: Image
      Architectures:
      - x86_64
    Metadata:
      Dockerfile: ./hello_world/Dockerfile
      DockerContext: ./
      DockerTag: python3.10
  HelloLayer:
    Type: AWS::Serverless::LayerVersion
    Properties: 
      LayerName: hello_layer
      ContentUri: ./layers/hello_layer/
      CompatibleRuntimes:
        - python3.10
      RetentionPolicy: Retain
    Metadata:
      BuildMethod: python3.10
